---
- hosts: localhost
  vars_files:
    - "vars/user.yml"
    - "vars/fedora.yml"
    - "vars/linux.yml"
    - "vars/macos.yml"
  vars:
    zellij_config_path: "$HOME/{{(ansible_os_family == 'Darwin') | ternary('/Library/Application Support/org.Zellij-Contributors.Zellij', '.config/zellij')}}"
    code_config_path: "$HOME/{{(ansible_os_family == 'Darwin') | ternary('Library/Application Support/', '.config/')}}Code - Insiders/User"
  tasks:
    - name: System configuration
      block:
        - name: Fedora system configuration
          import_tasks: tasks/fedora.yml
          when: ansible_os_family == "RedHat"
          tags: ["fedora"]
        - name: macOS system configration
          import_tasks: tasks/macos.yml
          when: ansible_os_family == "Darwin"
          tags: ["mac"]
          become: false
          become_user: "{{ user }}"
        - name: systemd
          import_tasks: tasks/systemd.yml
          when: ansible_os_family != "Darwin"
          tags: ["systemd"]
      tags: ["system"]
      become: true

    - name: User configuration
      block:
        - name: Config files
          import_tasks: tasks/config.yml
          tags: ["config"]
        - name: Fonts
          import_tasks: tasks/fonts.yml
          tags: ["fonts"]
        - name: Git
          import_tasks: tasks/git.yml
          tags: ["git"]
        - name: Neovim
          import_tasks: tasks/neovim.yml
          tags: ["neovim"]
        - name: rustup
          import_tasks: tasks/rustup.yml
          tags: ["rustup"]
        - name: pyenv
          import_tasks: tasks/pyenv.yml
          tags: ["pyenv"]
        - name: Code
          import_tasks: tasks/code.yml
          tags: ["code"]
      tags: ["user"]
      become: false
      become_user: "{{ user }}"
