---
- hosts: localhost
  vars_files:
    - "vars/user.yml"
    - "vars/macos.yml"
    - "vars/redhat.yml"
    - "vars/flatpak.yml"
    - "vars/debian.yml"
    - "vars/ubuntu.yml"
    - "vars/arch.yml"
    - "vars/linux.yml"
  tasks:
    - name: System configuration
      block:
        - name: Linux system configuration
          import_tasks: tasks/linux.yml
          when: ansible_system == "Linux"
          tags: ["linux"]
        - name: macOS system configration
          import_tasks: tasks/macos.yml
          when: ansible_os_family == "Darwin"
          tags: ["mac"]
          become: false
          become_user: "{{ user }}"
      tags: ["system"]
      become: true
    - name: User configuration
      block:
        - name: Fonts
          import_tasks: tasks/fonts.yml
          tags: ["fonts"]
        - name: Git
          import_tasks: tasks/git.yml
          tags: ["git"]
        - name: rustup
          import_tasks: tasks/rustup.yml
          tags: ["rustup"]
        - name: Config files
          import_tasks: tasks/config.yml
          tags: ["config"]
        - name: Code
          import_tasks: tasks/code.yml
          tags: ["code"]
      tags: ["user"]
      become: false
      become_user: "{{ user }}"
