---
- hosts: localhost
  vars_files:
    - "vars/user.yml"
    - "vars/linux.yml"
    - "vars/macos.yml"
    - "vars/redhat.yml"
    - "vars/flatpak.yml"
  vars:
    zellij_config_path: "$HOME/{{(ansible_os_family == 'Darwin') | ternary('/Library/Application Support/org.Zellij-Contributors.Zellij', '.config/zellij')}}"
    code_config_path: "$HOME/{{(ansible_os_family == 'Darwin') | ternary('Library/Application Support/', '.config/')}}Code - Insiders/User"
    redhat_platform: "{{(ansible_facts['distribution'] == 'Fedora') | ternary('fedora', 'el') }}"
  tasks:
    - name: System configuration
      block:
        - name: RedHat system configuration
          import_tasks: tasks/redhat.yml
          when: ansible_os_family == "RedHat"
          tags: ["fedora", "rocky"]
        - name: Debian system configuration
          import_tasks: tasks/debian.yml
          when: ansible_os_family == "Debian"
          tags: ["ubuntu", "debian", "pop"]
        - name: macOS system configration
          import_tasks: tasks/macos.yml
          when: ansible_os_family == "Darwin"
          tags: ["mac"]
          become: false
          become_user: "{{ user }}"
        - name: Flatpak installation
          import_tasks: tasks/flatpak.yml
          when: ansible_os_family == "RedHat"
          tags: ["flatpak"]
        - name: systemd
          import_tasks: tasks/systemd.yml
          when: ansible_system == "Linux" 
          tags: ["systemd"]
      tags: ["system"]
      become: true

    - name: User configuration
      block:
        - name: Fonts
          import_tasks: tasks/fonts.yml
          tags: ["fonts"]
        - name: Git
          import_tasks: tasks/git.yml
          tags: ["git"]
        - name: Neovim
          import_tasks: tasks/neovim.yml
          tags: ["neovim"]
        - name: rustup
          import_tasks: tasks/rustup.yml
          tags: ["rustup"]
        - name: pyenv
          import_tasks: tasks/pyenv.yml
          tags: ["pyenv"]
        - name: Go
          import_tasks: tasks/go.yml
          tags: ["go"]
        - name: Flutter
          import_tasks: tasks/flutter.yml
          tags: ["flutter"]
        - name: Config files
          import_tasks: tasks/config.yml
          tags: ["config"]
        - name: Terminal
          import_tasks: tasks/terminal.yml
          tags: ["terminal"]
        - name: Android Studio
          import_tasks: tasks/android.yml
          tags: ["android"]
          when: ansible_system == "Linux"
        - name: Code
          import_tasks: tasks/code.yml
          tags: ["code"]
      tags: ["user"]
      become: false
      become_user: "{{ user }}"
