---
- name: Skip if Android Studio installed
  stat:
    path: $HOME/android-studio/bin/
  register: studio_installed
- name: Install Android Studio
  block:
    - name: Download Android Studio
      unarchive:
        src: "https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.3.1.16/android-studio-2021.3.1.16-linux.tar.gz"
        dest: "$HOME"
        remote_src: yes
      when: not studio_installed.stat.exists
    - name: Ensure desktop entry is created
      copy:
        src: "files/home/.local/share/applications/AndroidStudio.desktop"
        dest: "$HOME/.local/share/applications/AndroidStudio.desktop"
    - name: Ensure desktop icon is copied
      copy:
        src: "~/android-studio/bin/studio.svg"
        dest: "$HOME/.local/share/pixmaps/AndroidStudio.svg"
    - name: Update desktop database
      shell:
        cmd: update-desktop-database ~/.local/share/applications
      register: output
      failed_when: output.rc != 0
