---
- name: Ensure packages are installed
  community.general.pacman:
    name: "{{ pacman_packages_to_install }}"
    state: latest
- name: Update packages
  community.general.pacman:
    update_cache: true
    upgrade: true
- name: Ensure AUR packages are installed
  shell: "whoami && yay -S --noconfirm --noprogressbar --needed {{ aur_packages_to_install | join(' ')}}"
  register: output
  failed_when: output.rc != 0
  changed_when: false
  become_user: "{{ user }}"
  tags: ["aur"]
