---
- name: Ensure packages are installed
  community.general.pacman:
    name: "{{ pacman_packages_to_install }}"
    state: present
- name: Update packages
  community.general.pacman:
    update_cache: true
    upgrade: true
