---
- name: Get config path
  set_fact:
    code_config_path: "$HOME/{{(ansible_os_family == 'Darwin') | ternary('Library/Application Support/', '.config/')}}Code/User"
- name: Ensure Code directory is created
  file:
    path: "{{ code_config_path }}"
    state: directory
- name: Ensure Code settings.json is created
  copy:
    src: files/home/.config/Code/User/settings.json
    dest: "{{ code_config_path }}/settings.json"
- name: Code extensions installation
  shell: "code --install-extension {{ item }}"
  loop: "{{ code_extensions_to_install }}"
  register: output
  failed_when: output.rc != 0
  changed_when: '"already installed" not in output.stdout'
  tags: ["code"]
