---
- name: Import keys
  shell:
    cmd: "curl -sS {{ item.value }} | gpg --dearmor | sudo tee /usr/share/keyrings/{{ item.key }}-archive-keyring.gpg"
  loop: "{{ apt_keys | dict2items }}"
- name: Add repositories
  apt_repository:
    repo: "{{ item.value }}"
    filename: "{{ item.key }}"
    state: present
  loop: "{{ apt_repositories | dict2items }}"
- name: Install packages
  apt:
    pkg: "{{ apt_packages_to_install }}"
    state: present
  tags: ["install-packages"]
- name: Remove packages
  apt:
    pkg: "{{ apt_packages_to_remove }}"
    state: absent
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
