---
- name: Add flathub
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
- name: Install flatpaks
  flatpak:
    name: "{{ flatpaks_to_install }}"
    remote: flathub
- name: Update flatpaks
  command: "flatpak update --noninteractive"
  register: output
  failed_when: output.rc != 0
  changed_when: output.stdout != "Nothing to do."