---
- name: Ensure nvim folder is created
  file:
    path: $HOME/.config/nvim
    state: directory
- name: Ensure init.lua is copied
  copy:
    src: files/home/.config/nvim/init.lua
    dest: $HOME/.config/nvim/init.lua
- name: Ensure nvim packages are installed
  shell: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync' +qa"
  register: output
  failed_when: output.rc != 0
  changed_when: false
- name: Ensure treesitter is updated
  shell: "nvim --headless +TSUpdateSync +qa"
  register: output
  failed_when: output.rc != 0
  changed_when: false
