---
- name: Ensure max_paralell_downloads is max
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: max_parallel_downloads
    value: 20
    no_extra_spaces: yes
- name: Get RedHat platform
  set_fact:
    redhat_platform: "{{(ansible_facts['distribution'] == 'Fedora') | ternary('fedora', 'el') }}"
- name: Install and enable the free RPM Fusion repositories
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/nonfree/{{redhat_platform}}/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/free/{{redhat_platform}}/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    disable_gpg_check: yes
- name: Import RPM keys
  rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ rpm_keys }}"
- name: Add dnf repositories
  copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
  loop: "{{ dnf_repositories }}"
- name: Install packages
  dnf:
    name: "{{ dnf_packages_to_install }}"
    state: present
- name: Install Fedora-specific packages
  dnf:
    name: "alacritty starship ripgrep skim"
- name: Remove unwanted packages
  dnf:
    name: "{{ dnf_packages_to_remove }}"
    state: absent
- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes
