---
- name: rustup
  block:
    - name: Skip if rustup is installed
      shell: rustup -V
      args:
        executable: /bin/bash
      register: rustup_installed
      changed_when: false
      failed_when: false
    - name: rustup installation
      block:
        - name: Download rustup
          uri:
            url: https://sh.rustup.rs
            return_content: yes
          register: rustup_installer
        - name: Run rustup installer
          shell:
            cmd: sh -s -- -y
            stdin: "{{ rustup_installer.content }}"
          register: output
          changed_when: '"Rust is installed now" in output.stdout'
          failed_when: output.rc != 0
        - name: Ensure bash completions folder is created
          file:
            path: $HOME/.local/share/bash-completion/completions
            state: directory
        - name: Bash completions
          shell: $HOME/.cargo/bin/rustup completions bash > ~/.local/share/bash-completion/completions/rustup && $HOME/.cargo/bin/rustup completions bash cargo > ~/.local/share/bash-completion/completions/cargo
          register: output
          failed_when: output.rc != 0
      when: "rustup_installed.rc != 0"
