---
- name: Set packages
  set_fact:
    terminal_packages: "{{ redhat_platform }} == 'el' | ternary('zellij alacritty ripgrep starship skim', 'zellij')"

- name: Install cargo packages
  shell: "$HOME/.cargo/bin/cargo install {{ terminal_packages }}"
  register: output
  failed_when: output.rc != 0
  tags: ["terminal"]
- name: Setup Alacritty desktop file
  block:
    - name: Ensure applications folder is created
      file:
        path: $HOME/.local/share/applications
        state: directory
    - name: Ensure pixmaps folder is created
      file:
        path: $HOME/.local/share/pixmaps
        state: directory
    - name: Ensure Alacritty desktop file is copied
      template:
        src: "templates/Alacritty.desktop.j2"
        dest: "$HOME/.local/share/applications/Alacritty.desktop"
    - name: Ensure Alacritty icon is copied
      copy:
        src: "files/home/.local/share/pixmaps/Alacritty.svg"
        dest: "$HOME/.local/share/pixmaps/Alacritty.svg"
    - name: Update desktop database
      shell:
        cmd: update-desktop-database ~/.local/share/applications
      register: output
      failed_when: output.rc != 0
  when: "ansible_os_family != 'Darwin' and {{ redhat_platform }} == 'el'"
  tags: ["terminal"]
